---
title: "Data Import"
output: github_document
---

This file is for doing data import. 

```{r}
library(tidyverse)
library(readxl)
library(haven)
```
# Import two CSVs

Import our first dataset. 

```{r}
litters_df = 
  read_csv(
    file = "Data/FAS_litters.csv", 
    na = c("NA", ".")
    )

litters_df = janitor::clean_names(litters_df)
```

Import your second dataset. 

```{r}
pups_df = 
  read_csv(file = "Data/FAS_pups.csv", 
           skip = 3,
           na = c("NA", ".")
           )

pups_df = janitor::clean_names(pups_df)
```

# Look at the data

```{r}
litters_df
pups_df
```

Head or tail
```{r}
head(litters_df) # first six rows by default
tail(pups_df) # last six rows by default 
```

Skimming
```{r}
skimr::skim(pups_df)
```

## Oh excel ... 

Jennry Bran made `readxl` to solve our problems. 
```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

Look at the data!
```{r}
mlb_df
```

Load some LOTR data. 

```{r}
fotr_df = 
  read_excel(
    "data/LotR_Words.xlsx", 
    range = "B3:D6")

fotr_df
```

```{r}
tt_df = 
  read_excel(
    "data/LotR_Words.xlsx", 
    range = "F3:H6")

tt_df
```

## Import SAS

Read in the PULSE dataset. 

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```

Import pups with `read.csv`

```{r, eval = FALSE}
pups_df_base = 
  read.csv("data/FAS_pups.csv")

pups_df_base
```

Won't show: lazy about variable names; super slow for big dataset. 



