---
title: "Data Tidying"
output: github_document
---

This file is for doing data tidying 

```{r}
library(tidyverse)
```

## Let's tidy some data!

```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()
```

Okay, let's tidy!
```{r}
pulse_tidy_df = 
  pulse_df |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi_score",
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )
```

Let's practice! Import the litters data, keep columns litter number and GD weights, and tidy

```{r}
litters_df_tidy = 
  read_csv(
    "data/FAS_litters.csv",
    na = c("", "NA", ".")
  ) |> 
  janitor::clean_names() |> 
  select(litter_number, gd0_weight, gd18_weight) |> 
  pivot_longer(
    c(gd0_weight, gd18_weight),
    names_to = "gestational_day",
    values_to = "weight"
  ) |> 
  mutate(
    gestational_day = case_match(
      gestational_day, 
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )
```

## Deliberately untidy data

```{r}
analysis_df = 
  tibble(
    groups = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean_outcome = c(4, 8, 3.5, 4.6)
  )
```

```{r}
analysis_df |> 
  pivot_wider(
    names_from = "time",
    values_from = mean_outcome
  ) |> 
  knitr::kable()
```

### bind some rows

```{r}
fellowship_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "B3:D6") |> 
  mutate(
    movie = "fellowship"
  )

two_towers_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "F3:H6") |> 
  mutate(
    movie = "two towers"
  )

return_of_king_df = 
  readxl::read_excel("data/LotR_Words.xlsx", range = "J3:L6") |> 
  mutate(
    movie = "return of king"
  )
```


```{r}
lotr_df = 
  bind_rows(fellowship_df, two_towers_df, return_of_king_df) |> 
  janitor::clean_names() |> 
  relocate(movie) |> 
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )
```


```{r}
pups_df = 
  read_csv(
    "data/FAS_pups.csv",
    skip = 3,
    na = c(".", "", "NA")
  ) |> 
  janitor::clean_names() |> 
  mutate(
    sex = 
      case_match(
        sex, 
        1 ~ "male", 
        2 ~ "female"),
    sex = as.factor(sex))

litters_df= 
  read_csv(
    "data/FAS_litters.csv",
    na = c("", "NA", ".")
  ) |> 
  janitor::clean_names() |> 
  relocate(litter_number) |> 
  separate(group, into = c("dose", "day_of_tx"), 3) |> 
  mutate(
    dose = str_to_lower(dose),
    day_of_tx = as.numeric(day_of_tx),
    gd_weight_gain = gd18_weight - gd0_weight
  )

fas_df =
  left_join(pups_df, litters_df, by = "litter_number")
```







